PROTO_DIR := proto
GOIMPORTS := $(shell go env GOPATH)/bin/goimports

server:
	go run cmd/main.go

protos:
	@go install golang.org/x/tools/cmd/goimports@v0.1.12
	@go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0
	@go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1
	@protoc \
	  --experimental_allow_proto3_optional \
	  --proto_path=$(PROTO_DIR) \
	  --go_out=paths=source_relative:$(PROTO_DIR) \
	  --go-grpc_out=require_unimplemented_servers=false,paths=source_relative:$(PROTO_DIR) \
	  $(PROTO_DIR)/payment/*.proto \
	  $(PROTO_DIR)/user/*.proto
	@$(GOIMPORTS) -w $(PROTO_DIR)
.PHONY: protos

code-gen:
	go run scaffolds/main.go
PHONY: code-gen

docs:
	echo "Starting swagger generating"
	go install github.com/swaggo/swag/cmd/swag@latest
	swag fmt
	swag init --parseDependency -g cmd/main.go
.PHONY: docs