// Code generated by scaffolds. DO NOT EDIT.
package service

import(
    "event_sourcing_gateway/package/settings"
    "event_sourcing_gateway/application/routing/delivery/remote"
    "event_sourcing_gateway/application/routing/delivery/remote/grpc"
)

func initRemoteServiceClientRegistry(config *settings.Config) map[string]RemoteServiceClient {
    return map[string]RemoteServiceClient {
        "PaymentService": remote.NewGrpcServiceClient(grpc.NewPaymentServiceClient(config)),
    }
}
