// Code generated by scaffolds. DO NOT EDIT.
package delivery

import (
	"event_sourcing_gateway/application/routing/delivery/handler"
	"event_sourcing_gateway/application/routing/delivery/handler/payment"
	"event_sourcing_gateway/application/routing/delivery/handler/user"
	"event_sourcing_gateway/package/settings"
)

type routingConfig struct {
	handler                 handler.RequestHandler
	remoteServiceName       string
	remoteServiceMethod     string
	remoteServicePermission string
}

func buildRegistry(cfg *settings.Config) map[string]routingConfig {
	return map[string]routingConfig{
		"GET:/api/v1/payment-service/balance": {
			payment.NewGetBalanceHandler(cfg),
			"PaymentService",
			"GetBalance",
			"",
		},
		"POST:/api/v1/user-service/user/create": {
			user.NewCreateUserHandler(cfg),
			"UserService",
			"CreateUser",
			"",
		},
		"POST:/api/v1/user-service/auth/login": {
			user.NewLoginHandler(cfg),
			"UserService",
			"Login",
			"",
		},
		"POST:/api/v1/user-service/auth/refresh": {
			user.NewRefreshHandler(cfg),
			"UserService",
			"Refresh",
			"",
		},
	}
}
