// Code generated by scaffolds. DO NOT EDIT.
package delivery

import (
	"github.com/gin-gonic/gin"
)

func (h *RoutingHandler) RegisterAPI(routes *gin.RouterGroup) {
	routes.GET("/balance", h.handle())
}
