// Code generated by scaffolds. DO NOT EDIT.
package grpc

import (
	"fmt"

	"event_sourcing_gateway/package/settings"
	"event_sourcing_gateway/proto/payment"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/resolver"

	"event_sourcing_gateway/package/grpc"
	"event_sourcing_gateway/package/monitor"
	"event_sourcing_gateway/package/svcdisc"
)

func (client *paymentServiceClient) initMethodRegistry() {
	client.methodRegistry = map[string]func(interface{}, map[string]string) (interface{}, error){
		"GetBalance": client.getBalance,
	}
}

type paymentServiceClient struct {
	grpcClient     payment.PaymentServiceClient
	methodRegistry map[string]func(interface{}, map[string]string) (interface{}, error)
}

func NewPaymentServiceClient(config *settings.Config) *paymentServiceClient {
	// using WithInsecure() because no SSL running
	consul := svcdisc.NewConsul(config)
	resolver.Register(consul.NewResolverBuilder(config.Service.PaymentServiceName))

	cc, err := grpc.CreateGRPCClientConn(
		fmt.Sprintf("consul:///%s", config.Service.PaymentServiceName),
		false,
	)
	if err != nil {
		fmt.Println("Could not connect:", err)
		return nil
	}

	client := paymentServiceClient{
		grpcClient: payment.NewPaymentServiceClient(cc),
	}
	client.initMethodRegistry()

	return &client
}

func (client *paymentServiceClient) GetMethodRegistry() map[string]func(interface{}, map[string]string) (interface{}, error) {
	return client.methodRegistry
}

func (client *paymentServiceClient) getBalance(data interface{}, md map[string]string) (interface{}, error) {
	ctx := monitor.GetApmContext()
	//ctx := context.Background()
	for k, v := range md {
		ctx = metadata.AppendToOutgoingContext(ctx, k, v)
	}
	return client.grpcClient.GetBalance(ctx, data.(*payment.GetBalanceRequest))
}
