// Code generated by scaffolds. DO NOT EDIT.
package application

func (s *Server) initPaymentRouting() {
	h := s.handler
	router := s.router.Group("")

	rPaymentPayment := router.Group("/api/v1/payment-service")
	rPaymentPayment.Use(h.Authorization())
	h.RegisterAPI(rPaymentPayment)
}
