// Code generated by scaffolds. DO NOT EDIT.
package application

func (s *Server) initPaymentRouting() {
	h := s.handler
	router := s.router.Group("")

	rPaymentPayment := router.Group("/api/v1/payment-service")
	rPaymentPayment.Use(h.Authorization())
	h.RegisterAPI(rPaymentPayment)
}

func (s *Server) initUserRouting() {
	h := s.handler
	router := s.router.Group("")

	rUserUser := router.Group("/api/v1/user-service")
	rUserUser.Use(h.Authorization())
	h.RegisterAPIUserService(rUserUser)
}
