// Code generated by scaffolds. DO NOT EDIT.
package payment

import(
    "strconv"
    
    

    "event_sourcing_gateway/proto/payment"
    "event_sourcing_gateway/package/settings"

    "event_sourcing_gateway/package/wrapper"
    "event_sourcing_gateway/package/monitor"
    "go.elastic.co/apm/v2"
)

type getBalanceHandler struct {
}

func NewGetBalanceHandler(cfg *settings.Config) *getBalanceHandler {
    return &getBalanceHandler{}
}

// @Summary permission: 
// @Tags PaymentService
// @Produce json
// @Param id  query  int64 false " "
// @Success 200 {object} payment.GetBalanceResponse
// @Router /api/v1/payment-service/balance [get]
func (handler *getBalanceHandler) Handle(ctx *wrapper.Context) (interface{}, error) {
    monitor.SetApmContext(apm.DetachedContext(ctx.Request.Context()))
    data := &payment.GetBalanceRequest{}
    idStr := ctx.Query("id")
    if idStr != "" {
        idValue, err := strconv.ParseInt(idStr, 10, 64)
        if err != nil {
            return nil, err
        }
        data.Id = idValue
    }


    return data, nil
}
